### ISSUE TITLE
utensor-cgen does not work with latest tensorflow (2.2.0)

### ISSUE THREAD

**Issue by jonassvedas** [uTensor/utensor_cgen#114]
I am getting this error when trying to run utensor_cgen with tensorflow 2.2.0:
`pkg_resources.DistributionNotFound: The 'tensorflow==2.1.0' distribution was not found and is required by utensor-cgen`
Is this a hard requirement or can it be updated to support tf 2.2.0? (edited)

**Comment by dboyliao** [comment]
Since `Tensorflow` constantly doing breaking features along the way in their low level api such as updating flatbuffer schema, which `utensor_cgen` may relies on, it's not practical for me to keep track of latest version of `Tensorflow` when developing this package.

You can update `setup.py` and run tests locally to see if latest TF breaks anything.
If everything goes well, I'm ok upgrading TF version.

**Comment by victorromeo** [comment]
Pull request added.  As I prefer to baseline at current stable version, this is for TensorFlow 2.3.1. not TF2.2.0 which is now legacy. See #137
